apiVersion: v1
kind: ServiceAccount
metadata:
  name: perisco-account
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: perisco-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: perisco-account
subjects:
  - kind: ServiceAccount
    name: perisco-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: perisco-role
  apiGroup: "rbac.authorization.k8s.io"