apiVersion: v1
kind: Namespace
metadata:
  name: perisco-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: perisco-account
  namespace: perisco-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: perisco-account
  namespace: perisco-system
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: perisco-account
subjects:
  - kind: ServiceAccount
    name: perisco-account
    namespace: perisco-system
roleRef:
  kind: ClusterRole
  name: perisco-account
  apiGroup: "rbac.authorization.k8s.io"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: perisco
  namespace: perisco-system
spec:
  selector:
    matchLabels:
      name: perisco
  template:
    metadata:
      labels:
        name: perisco
    spec:
      serviceAccountName: perisco-account
      containers:
      - name: perisco
        image: kbzjung359/perisco:0.0.2
        securityContext:
          privileged: true
          capabilities:
            add: 
            - SYS_ADMIN
            - SYS_PTRACE
        ports:
          - name: service
            containerPort: 8000
            hostPort: 30111
        env:
        - name: PERISCO_CIDRS
          value: 10.244.0.0/16,::ffff:10.244.0.0/112
        - name: PERISCO_PROTOS
          value: HTTP/1,MySQL
        - name: PERISCO_KUBERNETES
          value: 'true'
        - name: PERISCO_SERVER_PORT
          value: "8000"
        - name: PERISCO_SERVER_DEBUG_HANDLER
          value: 'true'
        # - name: PERISCO_EXPORTER_FILE_NAME
        #   value: /tmp/perisco-output.txt

