{
 "title": "Perisco k8s logs Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expression": "$A / $B", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Request Count Per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "serverService.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "protoMessage.ts", "id": "2", "settings": { "interval": "10s", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "protoMessage.ts"
    }
   ]
  },
  {
   "title": "Services Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "serverService.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "protoMessage.ts", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "protoMessage.l7.latencyNs", "id": "1", "settings": { "percents": [ "95" ], "script": "_value / 1000000" }, "type": "percentiles" }
     ],
     "timeField": "protoMessage.ts"
    }
   ]
  },
  {
   "title": "Services Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "serverService.name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "protoMessage.ts", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "protoMessage.l7.latencyNs", "id": "1", "settings": { "percents": [ "50" ], "script": "_value / 1000000" }, "type": "percentiles" }
     ],
     "timeField": "protoMessage.ts"
    }
   ]
  },
  {
   "title": "Pods Map",
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client.podName",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "server.podName",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "protoMessage.ts"
    }
   ]
  },
  {
   "title": "Requests Count Per Pod",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "server.podName",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "protoMessage.ts"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "ts"
    }
   ]
  }
 ]
}