// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: perisco.proto

package perisco

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPVersion int32

const (
	IPVersion_IP_UNKNOWN IPVersion = 0
	IPVersion_IPv4       IPVersion = 1
	IPVersion_IPv6       IPVersion = 2
)

// Enum value maps for IPVersion.
var (
	IPVersion_name = map[int32]string{
		0: "IP_UNKNOWN",
		1: "IPv4",
		2: "IPv6",
	}
	IPVersion_value = map[string]int32{
		"IP_UNKNOWN": 0,
		"IPv4":       1,
		"IPv6":       2,
	}
)

func (x IPVersion) Enum() *IPVersion {
	p := new(IPVersion)
	*p = x
	return p
}

func (x IPVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_perisco_proto_enumTypes[0].Descriptor()
}

func (IPVersion) Type() protoreflect.EnumType {
	return &file_perisco_proto_enumTypes[0]
}

func (x IPVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPVersion.Descriptor instead.
func (IPVersion) EnumDescriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{0}
}

type MySQLCommand int32

const (
	MySQLCommand_COM_UNKNOWN             MySQLCommand = 0
	MySQLCommand_COM_QUERY               MySQLCommand = 1
	MySQLCommand_COM_QUIT                MySQLCommand = 2
	MySQLCommand_COM_INIT_DB             MySQLCommand = 3
	MySQLCommand_COM_FIELD_LIST          MySQLCommand = 4
	MySQLCommand_COM_REFRESH             MySQLCommand = 5
	MySQLCommand_COM_STATISTICS          MySQLCommand = 6
	MySQLCommand_COM_PROCESS_INFO        MySQLCommand = 7
	MySQLCommand_COM_PROCESS_KILL        MySQLCommand = 8
	MySQLCommand_COM_DEBUG               MySQLCommand = 9
	MySQLCommand_COM_PING                MySQLCommand = 10
	MySQLCommand_COM_CHANGE_USER         MySQLCommand = 11
	MySQLCommand_COM_RESET_CONNECTION    MySQLCommand = 12
	MySQLCommand_COM_SET_OPTION          MySQLCommand = 13
	MySQLCommand_COM_STMT_PREPARE        MySQLCommand = 14
	MySQLCommand_COM_STMT_EXECUTE        MySQLCommand = 15
	MySQLCommand_COM_STMT_FETCH          MySQLCommand = 16
	MySQLCommand_COM_STMT_CLOSE          MySQLCommand = 17
	MySQLCommand_COM_STMT_RESET          MySQLCommand = 18
	MySQLCommand_COM_STMT_SEND_LONG_DATA MySQLCommand = 19
)

// Enum value maps for MySQLCommand.
var (
	MySQLCommand_name = map[int32]string{
		0:  "COM_UNKNOWN",
		1:  "COM_QUERY",
		2:  "COM_QUIT",
		3:  "COM_INIT_DB",
		4:  "COM_FIELD_LIST",
		5:  "COM_REFRESH",
		6:  "COM_STATISTICS",
		7:  "COM_PROCESS_INFO",
		8:  "COM_PROCESS_KILL",
		9:  "COM_DEBUG",
		10: "COM_PING",
		11: "COM_CHANGE_USER",
		12: "COM_RESET_CONNECTION",
		13: "COM_SET_OPTION",
		14: "COM_STMT_PREPARE",
		15: "COM_STMT_EXECUTE",
		16: "COM_STMT_FETCH",
		17: "COM_STMT_CLOSE",
		18: "COM_STMT_RESET",
		19: "COM_STMT_SEND_LONG_DATA",
	}
	MySQLCommand_value = map[string]int32{
		"COM_UNKNOWN":             0,
		"COM_QUERY":               1,
		"COM_QUIT":                2,
		"COM_INIT_DB":             3,
		"COM_FIELD_LIST":          4,
		"COM_REFRESH":             5,
		"COM_STATISTICS":          6,
		"COM_PROCESS_INFO":        7,
		"COM_PROCESS_KILL":        8,
		"COM_DEBUG":               9,
		"COM_PING":                10,
		"COM_CHANGE_USER":         11,
		"COM_RESET_CONNECTION":    12,
		"COM_SET_OPTION":          13,
		"COM_STMT_PREPARE":        14,
		"COM_STMT_EXECUTE":        15,
		"COM_STMT_FETCH":          16,
		"COM_STMT_CLOSE":          17,
		"COM_STMT_RESET":          18,
		"COM_STMT_SEND_LONG_DATA": 19,
	}
)

func (x MySQLCommand) Enum() *MySQLCommand {
	p := new(MySQLCommand)
	*p = x
	return p
}

func (x MySQLCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MySQLCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_perisco_proto_enumTypes[1].Descriptor()
}

func (MySQLCommand) Type() protoreflect.EnumType {
	return &file_perisco_proto_enumTypes[1]
}

func (x MySQLCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MySQLCommand.Descriptor instead.
func (MySQLCommand) EnumDescriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{1}
}

type MySQLResponseType int32

const (
	MySQLResponseType_UNKNOWN MySQLResponseType = 0
	MySQLResponseType_OK      MySQLResponseType = 1
	MySQLResponseType_ERR     MySQLResponseType = 2
	MySQLResponseType_EOF     MySQLResponseType = 3
)

// Enum value maps for MySQLResponseType.
var (
	MySQLResponseType_name = map[int32]string{
		0: "UNKNOWN",
		1: "OK",
		2: "ERR",
		3: "EOF",
	}
	MySQLResponseType_value = map[string]int32{
		"UNKNOWN": 0,
		"OK":      1,
		"ERR":     2,
		"EOF":     3,
	}
)

func (x MySQLResponseType) Enum() *MySQLResponseType {
	p := new(MySQLResponseType)
	*p = x
	return p
}

func (x MySQLResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MySQLResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_perisco_proto_enumTypes[2].Descriptor()
}

func (MySQLResponseType) Type() protoreflect.EnumType {
	return &file_perisco_proto_enumTypes[2]
}

func (x MySQLResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MySQLResponseType.Descriptor instead.
func (MySQLResponseType) EnumDescriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{2}
}

type ProtoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamp.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Pid uint32               `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Ip  *IP                  `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	L4  *Layer4              `protobuf:"bytes,4,opt,name=l4,proto3" json:"l4,omitempty"`
	L7  *Layer7              `protobuf:"bytes,5,opt,name=l7,proto3" json:"l7,omitempty"`
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessage.ProtoReflect.Descriptor instead.
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMessage) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *ProtoMessage) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProtoMessage) GetIp() *IP {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *ProtoMessage) GetL4() *Layer4 {
	if x != nil {
		return x.L4
	}
	return nil
}

func (x *ProtoMessage) GetL7() *Layer7 {
	if x != nil {
		return x.L7
	}
	return nil
}

type IP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client    string    `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Server    string    `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	IpVersion IPVersion `protobuf:"varint,3,opt,name=ipVersion,proto3,enum=perisco.IPVersion" json:"ipVersion,omitempty"`
}

func (x *IP) Reset() {
	*x = IP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{1}
}

func (x *IP) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *IP) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *IP) GetIpVersion() IPVersion {
	if x != nil {
		return x.IpVersion
	}
	return IPVersion_IP_UNKNOWN
}

type Layer4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Protocol:
	//	*Layer4_TCP
	//	*Layer4_UDP
	Protocol isLayer4_Protocol `protobuf_oneof:"protocol"`
}

func (x *Layer4) Reset() {
	*x = Layer4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layer4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer4) ProtoMessage() {}

func (x *Layer4) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer4.ProtoReflect.Descriptor instead.
func (*Layer4) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{2}
}

func (m *Layer4) GetProtocol() isLayer4_Protocol {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (x *Layer4) GetTCP() *TCP {
	if x, ok := x.GetProtocol().(*Layer4_TCP); ok {
		return x.TCP
	}
	return nil
}

func (x *Layer4) GetUDP() *UDP {
	if x, ok := x.GetProtocol().(*Layer4_UDP); ok {
		return x.UDP
	}
	return nil
}

type isLayer4_Protocol interface {
	isLayer4_Protocol()
}

type Layer4_TCP struct {
	TCP *TCP `protobuf:"bytes,1,opt,name=TCP,proto3,oneof"`
}

type Layer4_UDP struct {
	UDP *UDP `protobuf:"bytes,2,opt,name=UDP,proto3,oneof"`
}

func (*Layer4_TCP) isLayer4_Protocol() {}

func (*Layer4_UDP) isLayer4_Protocol() {}

type TCP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientPort uint32 `protobuf:"varint,1,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ServerPort uint32 `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
}

func (x *TCP) Reset() {
	*x = TCP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TCP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCP) ProtoMessage() {}

func (x *TCP) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCP.ProtoReflect.Descriptor instead.
func (*TCP) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{3}
}

func (x *TCP) GetClientPort() uint32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *TCP) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

type UDP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientPort uint32 `protobuf:"varint,1,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ServerPort uint32 `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
}

func (x *UDP) Reset() {
	*x = UDP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDP) ProtoMessage() {}

func (x *UDP) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDP.ProtoReflect.Descriptor instead.
func (*UDP) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{4}
}

func (x *UDP) GetClientPort() uint32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *UDP) GetServerPort() uint32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

type Layer7 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatencyNs uint64    `protobuf:"varint,1,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	Request   *Request  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response  *Response `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *Layer7) Reset() {
	*x = Layer7{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layer7) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer7) ProtoMessage() {}

func (x *Layer7) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer7.ProtoReflect.Descriptor instead.
func (*Layer7) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{5}
}

func (x *Layer7) GetLatencyNs() uint64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *Layer7) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Layer7) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Record:
	//	*Request_Http
	//	*Request_Mysql
	Record isRequest_Record `protobuf_oneof:"record"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{6}
}

func (m *Request) GetRecord() isRequest_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *Request) GetHttp() *HTTPRequest {
	if x, ok := x.GetRecord().(*Request_Http); ok {
		return x.Http
	}
	return nil
}

func (x *Request) GetMysql() *MySQLRequest {
	if x, ok := x.GetRecord().(*Request_Mysql); ok {
		return x.Mysql
	}
	return nil
}

type isRequest_Record interface {
	isRequest_Record()
}

type Request_Http struct {
	Http *HTTPRequest `protobuf:"bytes,1,opt,name=http,proto3,oneof"`
}

type Request_Mysql struct {
	Mysql *MySQLRequest `protobuf:"bytes,2,opt,name=mysql,proto3,oneof"`
}

func (*Request_Http) isRequest_Record() {}

func (*Request_Mysql) isRequest_Record() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Record:
	//	*Response_Http
	//	*Response_Mysql
	Record isResponse_Record `protobuf_oneof:"record"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{7}
}

func (m *Response) GetRecord() isResponse_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *Response) GetHttp() *HTTPResponse {
	if x, ok := x.GetRecord().(*Response_Http); ok {
		return x.Http
	}
	return nil
}

func (x *Response) GetMysql() *MySQLResponse {
	if x, ok := x.GetRecord().(*Response_Mysql); ok {
		return x.Mysql
	}
	return nil
}

type isResponse_Record interface {
	isResponse_Record()
}

type Response_Http struct {
	Http *HTTPResponse `protobuf:"bytes,1,opt,name=http,proto3,oneof"`
}

type Response_Mysql struct {
	Mysql *MySQLResponse `protobuf:"bytes,2,opt,name=mysql,proto3,oneof"`
}

func (*Response_Http) isResponse_Record() {}

func (*Response_Mysql) isResponse_Record() {}

type HTTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string        `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method   string        `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url      string        `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers  []*HTTPHeader `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{8}
}

func (x *HTTPRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPRequest) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HTTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol string        `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Code     uint32        `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Headers  []*HTTPHeader `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{9}
}

func (x *HTTPResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HTTPResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HTTPResponse) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HTTPHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HTTPHeader) Reset() {
	*x = HTTPHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPHeader) ProtoMessage() {}

func (x *HTTPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPHeader.ProtoReflect.Descriptor instead.
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{10}
}

func (x *HTTPHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HTTPHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MySQLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayloadLength uint32       `protobuf:"varint,1,opt,name=payload_length,json=payloadLength,proto3" json:"payload_length,omitempty"`
	Command       MySQLCommand `protobuf:"varint,2,opt,name=command,proto3,enum=perisco.MySQLCommand" json:"command,omitempty"`
}

func (x *MySQLRequest) Reset() {
	*x = MySQLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MySQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLRequest) ProtoMessage() {}

func (x *MySQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLRequest.ProtoReflect.Descriptor instead.
func (*MySQLRequest) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{11}
}

func (x *MySQLRequest) GetPayloadLength() uint32 {
	if x != nil {
		return x.PayloadLength
	}
	return 0
}

func (x *MySQLRequest) GetCommand() MySQLCommand {
	if x != nil {
		return x.Command
	}
	return MySQLCommand_COM_UNKNOWN
}

type MySQLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         MySQLResponseType `protobuf:"varint,1,opt,name=type,proto3,enum=perisco.MySQLResponseType" json:"type,omitempty"`
	AffectedRows uint64            `protobuf:"varint,2,opt,name=affected_rows,json=affectedRows,proto3" json:"affected_rows,omitempty"`
	ErrorCode    uint32            `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *MySQLResponse) Reset() {
	*x = MySQLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MySQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLResponse) ProtoMessage() {}

func (x *MySQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLResponse.ProtoReflect.Descriptor instead.
func (*MySQLResponse) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{12}
}

func (x *MySQLResponse) GetType() MySQLResponseType {
	if x != nil {
		return x.Type
	}
	return MySQLResponseType_UNKNOWN
}

func (x *MySQLResponse) GetAffectedRows() uint64 {
	if x != nil {
		return x.AffectedRows
	}
	return 0
}

func (x *MySQLResponse) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type K8SProtoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtoMessage_ *ProtoMessage `protobuf:"bytes,1,opt,name=proto_message,json=protoMessage,proto3" json:"proto_message,omitempty"`
	Client        *Endpoint     `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Server        *Endpoint     `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	ClientService *Service      `protobuf:"bytes,4,opt,name=client_service,json=clientService,proto3" json:"client_service,omitempty"`
	ServerService *Service      `protobuf:"bytes,5,opt,name=server_service,json=serverService,proto3" json:"server_service,omitempty"`
}

func (x *K8SProtoMessage) Reset() {
	*x = K8SProtoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SProtoMessage) ProtoMessage() {}

func (x *K8SProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SProtoMessage.ProtoReflect.Descriptor instead.
func (*K8SProtoMessage) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{13}
}

func (x *K8SProtoMessage) GetProtoMessage_() *ProtoMessage {
	if x != nil {
		return x.ProtoMessage_
	}
	return nil
}

func (x *K8SProtoMessage) GetClient() *Endpoint {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *K8SProtoMessage) GetServer() *Endpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *K8SProtoMessage) GetClientService() *Service {
	if x != nil {
		return x.ClientService
	}
	return nil
}

func (x *K8SProtoMessage) GetServerService() *Service {
	if x != nil {
		return x.ServerService
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint32      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Identity  uint32      `protobuf:"varint,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Namespace string      `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels    []string    `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	PodName   string      `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Workloads []*Workload `protobuf:"bytes,6,rep,name=workloads,proto3" json:"workloads,omitempty"`
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{14}
}

func (x *Endpoint) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Endpoint) GetIdentity() uint32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

func (x *Endpoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Endpoint) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Endpoint) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Endpoint) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type Workload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *Workload) Reset() {
	*x = Workload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{15}
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perisco_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_perisco_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_perisco_proto_rawDescGZIP(), []int{16}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_perisco_proto protoreflect.FileDescriptor

var file_perisco_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x0c, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x49,
	0x50, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1f, 0x0a, 0x02, 0x6c, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x4c, 0x61, 0x79, 0x65,
	0x72, 0x34, 0x52, 0x02, 0x6c, 0x34, 0x12, 0x1f, 0x0a, 0x02, 0x6c, 0x37, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x37, 0x52, 0x02, 0x6c, 0x37, 0x22, 0x66, 0x0a, 0x02, 0x49, 0x50, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x30, 0x0a,
	0x09, 0x69, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x49, 0x50, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x69, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x58, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x34, 0x12, 0x20, 0x0a, 0x03, 0x54, 0x43, 0x50,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f,
	0x2e, 0x54, 0x43, 0x50, 0x48, 0x00, 0x52, 0x03, 0x54, 0x43, 0x50, 0x12, 0x20, 0x0a, 0x03, 0x55,
	0x44, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73,
	0x63, 0x6f, 0x2e, 0x55, 0x44, 0x50, 0x48, 0x00, 0x52, 0x03, 0x55, 0x44, 0x50, 0x42, 0x0a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x47, 0x0a, 0x03, 0x54, 0x43, 0x50,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f,
	0x72, 0x74, 0x22, 0x47, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x06,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x37, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x5f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6c, 0x61, 0x74, 0x65,
	0x6e, 0x63, 0x79, 0x4e, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2d, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x6e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x68,
	0x74, 0x74, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x65, 0x72, 0x69,
	0x73, 0x63, 0x6f, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x12, 0x2d, 0x0a, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f,
	0x2e, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x22, 0x71, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04,
	0x68, 0x74, 0x74, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x65, 0x72,
	0x69, 0x73, 0x63, 0x6f, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x12, 0x2e, 0x0a, 0x05, 0x6d, 0x79, 0x73,
	0x71, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73,
	0x63, 0x6f, 0x2e, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x0b, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x65, 0x72,
	0x69, 0x73, 0x63, 0x6f, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x6d, 0x0a, 0x0c, 0x48, 0x54, 0x54, 0x50,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x65, 0x72, 0x69,
	0x73, 0x63, 0x6f, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x07,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x34, 0x0a, 0x0a, 0x48, 0x54, 0x54, 0x50, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x66, 0x0a,
	0x0c, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e,
	0x4d, 0x79, 0x53, 0x51, 0x4c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x0d, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e,
	0x4d, 0x79, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x95, 0x02, 0x0a, 0x0f,
	0x4b, 0x38, 0x53, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x3a, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x65,
	0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f,
	0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x37, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x69,
	0x73, 0x63, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a,
	0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x22, 0x32,
	0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x22, 0x3b, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2a,
	0x2f, 0x0a, 0x09, 0x49, 0x50, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a,
	0x49, 0x50, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x50, 0x76, 0x34, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x50, 0x76, 0x36, 0x10, 0x02,
	0x2a, 0x97, 0x03, 0x0a, 0x0c, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4d, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x5f, 0x51, 0x55, 0x49, 0x54, 0x10, 0x02, 0x12,
	0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4d, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x5f, 0x44, 0x42, 0x10, 0x03,
	0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4d, 0x5f, 0x46, 0x49, 0x45, 0x4c, 0x44, 0x5f, 0x4c, 0x49,
	0x53, 0x54, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4d, 0x5f, 0x52, 0x45, 0x46, 0x52,
	0x45, 0x53, 0x48, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x49, 0x53, 0x54, 0x49, 0x43, 0x53, 0x10, 0x06, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4d,
	0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x07, 0x12,
	0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x4b,
	0x49, 0x4c, 0x4c, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x5f, 0x44, 0x45, 0x42,
	0x55, 0x47, 0x10, 0x09, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x5f, 0x50, 0x49, 0x4e, 0x47,
	0x10, 0x0a, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4d, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x0b, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4d, 0x5f, 0x52,
	0x45, 0x53, 0x45, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x0c, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4d, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x4f, 0x50, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x0d, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x4d,
	0x54, 0x5f, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x0e, 0x12, 0x14, 0x0a, 0x10, 0x43,
	0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x4d, 0x54, 0x5f, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x10,
	0x0f, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x4d, 0x54, 0x5f, 0x46, 0x45,
	0x54, 0x43, 0x48, 0x10, 0x10, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x4d,
	0x54, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x11, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4d,
	0x5f, 0x53, 0x54, 0x4d, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x54, 0x10, 0x12, 0x12, 0x1b, 0x0a,
	0x17, 0x43, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x4d, 0x54, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x4c,
	0x4f, 0x4e, 0x47, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x13, 0x2a, 0x3a, 0x0a, 0x11, 0x4d, 0x79,
	0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x52, 0x52, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x45, 0x4f, 0x46, 0x10, 0x03, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x75, 0x6d, 0x4b, 0x65, 0x65, 0x48, 0x79, 0x75, 0x6e, 0x2f,
	0x70, 0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x65, 0x72, 0x69, 0x73, 0x63, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_perisco_proto_rawDescOnce sync.Once
	file_perisco_proto_rawDescData = file_perisco_proto_rawDesc
)

func file_perisco_proto_rawDescGZIP() []byte {
	file_perisco_proto_rawDescOnce.Do(func() {
		file_perisco_proto_rawDescData = protoimpl.X.CompressGZIP(file_perisco_proto_rawDescData)
	})
	return file_perisco_proto_rawDescData
}

var file_perisco_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_perisco_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_perisco_proto_goTypes = []interface{}{
	(IPVersion)(0),              // 0: perisco.IPVersion
	(MySQLCommand)(0),           // 1: perisco.MySQLCommand
	(MySQLResponseType)(0),      // 2: perisco.MySQLResponseType
	(*ProtoMessage)(nil),        // 3: perisco.ProtoMessage
	(*IP)(nil),                  // 4: perisco.IP
	(*Layer4)(nil),              // 5: perisco.Layer4
	(*TCP)(nil),                 // 6: perisco.TCP
	(*UDP)(nil),                 // 7: perisco.UDP
	(*Layer7)(nil),              // 8: perisco.Layer7
	(*Request)(nil),             // 9: perisco.Request
	(*Response)(nil),            // 10: perisco.Response
	(*HTTPRequest)(nil),         // 11: perisco.HTTPRequest
	(*HTTPResponse)(nil),        // 12: perisco.HTTPResponse
	(*HTTPHeader)(nil),          // 13: perisco.HTTPHeader
	(*MySQLRequest)(nil),        // 14: perisco.MySQLRequest
	(*MySQLResponse)(nil),       // 15: perisco.MySQLResponse
	(*K8SProtoMessage)(nil),     // 16: perisco.K8SProtoMessage
	(*Endpoint)(nil),            // 17: perisco.Endpoint
	(*Workload)(nil),            // 18: perisco.Workload
	(*Service)(nil),             // 19: perisco.Service
	(*timestamp.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_perisco_proto_depIdxs = []int32{
	20, // 0: perisco.ProtoMessage.ts:type_name -> google.protobuf.Timestamp
	4,  // 1: perisco.ProtoMessage.ip:type_name -> perisco.IP
	5,  // 2: perisco.ProtoMessage.l4:type_name -> perisco.Layer4
	8,  // 3: perisco.ProtoMessage.l7:type_name -> perisco.Layer7
	0,  // 4: perisco.IP.ipVersion:type_name -> perisco.IPVersion
	6,  // 5: perisco.Layer4.TCP:type_name -> perisco.TCP
	7,  // 6: perisco.Layer4.UDP:type_name -> perisco.UDP
	9,  // 7: perisco.Layer7.request:type_name -> perisco.Request
	10, // 8: perisco.Layer7.response:type_name -> perisco.Response
	11, // 9: perisco.Request.http:type_name -> perisco.HTTPRequest
	14, // 10: perisco.Request.mysql:type_name -> perisco.MySQLRequest
	12, // 11: perisco.Response.http:type_name -> perisco.HTTPResponse
	15, // 12: perisco.Response.mysql:type_name -> perisco.MySQLResponse
	13, // 13: perisco.HTTPRequest.headers:type_name -> perisco.HTTPHeader
	13, // 14: perisco.HTTPResponse.headers:type_name -> perisco.HTTPHeader
	1,  // 15: perisco.MySQLRequest.command:type_name -> perisco.MySQLCommand
	2,  // 16: perisco.MySQLResponse.type:type_name -> perisco.MySQLResponseType
	3,  // 17: perisco.K8SProtoMessage.proto_message:type_name -> perisco.ProtoMessage
	17, // 18: perisco.K8SProtoMessage.client:type_name -> perisco.Endpoint
	17, // 19: perisco.K8SProtoMessage.server:type_name -> perisco.Endpoint
	19, // 20: perisco.K8SProtoMessage.client_service:type_name -> perisco.Service
	19, // 21: perisco.K8SProtoMessage.server_service:type_name -> perisco.Service
	18, // 22: perisco.Endpoint.workloads:type_name -> perisco.Workload
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_perisco_proto_init() }
func file_perisco_proto_init() {
	if File_perisco_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_perisco_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layer4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TCP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UDP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layer7); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MySQLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MySQLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*K8SProtoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perisco_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_perisco_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Layer4_TCP)(nil),
		(*Layer4_UDP)(nil),
	}
	file_perisco_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Request_Http)(nil),
		(*Request_Mysql)(nil),
	}
	file_perisco_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Response_Http)(nil),
		(*Response_Mysql)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_perisco_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_perisco_proto_goTypes,
		DependencyIndexes: file_perisco_proto_depIdxs,
		EnumInfos:         file_perisco_proto_enumTypes,
		MessageInfos:      file_perisco_proto_msgTypes,
	}.Build()
	File_perisco_proto = out.File
	file_perisco_proto_rawDesc = nil
	file_perisco_proto_goTypes = nil
	file_perisco_proto_depIdxs = nil
}
