apiVersion: v2
name: perisco
version: 0.0.1
sources:
  - https://github.com/KumKeeHyun/perisco
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co
    version: 7.17.3
    condition: elasticsearch.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.59.0
    condition: grafana.enabled
  