perisco:
  image:
    repository: kbzjung359/perisco
    tag: 0.0.2
    pullPolicy: Always

  config:
    cidrs: 10.244.0.0/16,::ffff:10.244.0.0/112
    protocols: HTTP/1,MySQL

  server:
    hostPort: 30111
    debug: true
  
  exporter:
    name: elasticsearch
    elasticsearch:
      addresses: http://elasticsearch-master:9200

  resources:
    requests:
      memory: "512Mi"
      cpu: "150m"
    limits:
      memory: "2048Mi"

elasticsearch:
  enabled: true

  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'

  readinessProbe:
   failureThreshold: 3
   initialDelaySeconds: 20
   periodSeconds: 10
   successThreshold: 3
   timeoutSeconds: 5
  
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi

  resources:
    requests:
      cpu: "300m"
      memory: "1Gi"
    # limits:
    #   cpu: "500m"
    #   memory: "2Gi"

grafana:
  enabled: true

  adminPassword: admin

  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 31000

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: elasticsearch
        type: elasticsearch 
        access: proxy
        url: http://elasticsearch-master:9200
        uid: perisco-elasticsearch
        jsonData:
          index: 'perisco-k8s-logs-*'
          timeField: 'protoMessage.ts'
  
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'perisco'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/perisco
    
  dashboardsConfigMaps:
    perisco: perisco-dashboard-files
