version: '3'
services:
  grafana:
    image: grafana/grafana:9.4.7
    ports:
      - 3000:3000
  kibana:
    image: kibana:7.17.9
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - cluster.name=elasticsearch
      - node.name=es
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/data:/elasticsearch/data
    ports:
      - 9200:9200